### ISSUE TITLE
不使用docker部署，请问配置文件怎么配

### ISSUE THREAD

**Issue by ezrajiang** [anyidea/chatgpt-dingtalk-bot#27]
如果不使用docker部署，请问配置文件怎么配，必须安装的Python库有哪些？

**Comment by anyidea** [comment]
参考
<img width="895" alt="CleanShot 2023-08-21 at 15 00 36@2x" src="https://github.com/anyidea/chatgpt-dingtalk-bot/assets/48710760/25f6da6c-7e85-4d1f-93ec-b7fb2f82ce8b">
配置文件直接复制 .env.dist 重命名为.env并且根据自己情况修改变量即可

**Comment by ezrajiang** [comment]
> 参考 <img alt="CleanShot 2023-08-21 at 15 00 36@2x" width="895" src="https://user-images.githubusercontent.com/48710760/261944044-25f6da6c-7e85-4d1f-93ec-b7fb2f82ce8b.png"> 配置文件直接复制 .env.dist 重命名为.env并且根据自己情况修改变量即可


报这个错误
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/content/chatgpt-dingtalk-bot/chatbot/__main__.py", line 1, in <module>
    from .main import main
  File "/content/chatgpt-dingtalk-bot/chatbot/main.py", line 3, in <module>
    from dingtalk_stream import AckMessage
ModuleNotFoundError: No module named 'dingtalk_stream'
